<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Chromatic_Sensitivity</RootNamespace>
    <AssemblyName>Chromatic_Sensitivity_1.5</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <AllowedReferenceRelatedFileExtensions>None</AllowedReferenceRelatedFileExtensions>
    <LangVersion>latest</LangVersion>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ModName>$(MSBuildProjectName)</ModName>
    <SteamModsPath>$(RIMWORLD_STEAM_MODS_PATH)</SteamModsPath>
    <SteamPath>$(RIMWORLD_STEAM_PATH)</SteamPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>TRACE;DEBUG</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>../../../Debug/1.5/Assemblies</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
	  <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <OutputPath>../../../Assemblies/1.5/Assemblies</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="AlienRace">
      <HintPath Condition="Exists('../../../../AlienRaces/1.5/Assemblies/AlienRace.dll')">../../../../AlienRaces/1.5/Assemblies/AlienRace.dll</HintPath>
      <HintPath Condition="!Exists('../../../../AlienRaces/1.5/Assemblies/AlienRace.dll')">../../../../839005762/1.5/Assemblies/AlienRace.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.*" ExcludeAssets="runtime" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5-*"/>
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../../../../Data/*/Defs/**/*">
      <Link>AttachedDefs/Rimworld/%(RecursiveDir)/%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="../../Defs/**/*">
      <Link>AttachedDefs/Project/%(RecursiveDir)/%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <PropertyGroup>
    <StartAction>Program</StartAction>
    <StartProgram>../../../../../RimWorldWin64.exe</StartProgram>
  </PropertyGroup>
  <Target Name="Clean">
    <RemoveDir Directories="$(OutputPath)" />
  </Target>  
</Project>
